"""empty message

Revision ID: 49dbf1a76b46
Revises: a2f7a449f2b0
Create Date: 2017-05-25 11:39:14.698830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dbf1a76b46'
down_revision = 'a2f7a449f2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('textcolor', sa.String(length=255), nullable=True),
    sa.Column('textcontent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markers')
    op.drop_table('image')
    op.drop_table('file')
    # ### end Alembic commands ###
